export type StitchCategoryId = "assemble" | "edit" | "convert" | "secure";

export type StitchBadgeTone =
  | "popular"
  | "secondary"
  | "slate"
  | "tertiary"
  | "primaryFixed"
  | "emerald"
  | "amber"
  | "brand";

export type StitchTool = {
  id: string;
  name: string;
  description: string;
  href: string;
  category: StitchCategoryId;
  icon: string;
  badge: string;
  badgeTone: StitchBadgeTone;
  footer: string;
  tag: string;
  searchText: string;
  iconTone?: "brand" | "amber";
};

export type StitchCategory = {
  id: StitchCategoryId;
  index: string;
  title: string;
  blurb: string;
  icon: string;
  count: number;
};

export const stitchCategories: StitchCategory[] = [
  {
    id: "assemble",
    index: "01",
    title: "Assemble",
    blurb: "Combine, split, extract, and arrange pages",
    icon: "layers",
    count: 10,
  },
  {
    id: "edit",
    index: "02",
    title: "Edit & Sign",
    blurb: "Annotate, redact, stamp, and fill documents",
    icon: "edit_note",
    count: 5,
  },
  {
    id: "convert",
    index: "03",
    title: "Convert",
    blurb: "Format conversion, OCR, scan, handwriting, summaries, and image exports",
    icon: "sync_alt",
    count: 8,
  },
  {
    id: "secure",
    index: "04",
    title: "Security & Repair",
    blurb: "Local cryptographic lock, unlock, and document recovery",
    icon: "security",
    count: 3,
  },
];

export const stitchTools: StitchTool[] = [
  {
    id: "merge",
    name: "Merge PDF",
    description: "Combine PDFs and images in the exact order you choose.",
    href: "/pdf-tools/merge",
    category: "assemble",
    icon: "call_merge",
    badge: "Popular",
    badgeTone: "popular",
    footer: "Lossless stitching",
    tag: "PDF + Img",
    searchText: "merge pdf combine losslessly images",
  },
  {
    id: "split",
    name: "Split & Extract",
    description: "Save selected pages or page ranges as a new PDF.",
    href: "/pdf-tools/split",
    category: "assemble",
    icon: "call_split",
    badge: "Precise",
    badgeTone: "slate",
    footer: "Custom page ranges",
    tag: "1-N Split",
    searchText: "split and extract pages ranges",
  },
  {
    id: "organise",
    name: "Organise Pages",
    description: "Reorder, rotate, flip, or remove pages with a visual preview.",
    href: "/pdf-tools/organise",
    category: "assemble",
    icon: "grid_view",
    badge: "Visual",
    badgeTone: "slate",
    footer: "Drag & reorder",
    tag: "Canvas Tile",
    searchText: "organise organize pages visual reorder rotate flip remove",
  },
  {
    id: "rotate",
    name: "Rotate PDF",
    description: "Rotate all or selected pages by 90° steps.",
    href: "/pdf-tools/rotate",
    category: "assemble",
    icon: "rotate_right",
    badge: "90°",
    badgeTone: "slate",
    footer: "Same engine as Organise",
    tag: "Vector rotate",
    searchText: "rotate pdf pages orientation turn 90",
  },
  {
    id: "flip",
    name: "Flip PDF",
    description: "Mirror pages horizontally or vertically.",
    href: "/pdf-tools/flip",
    category: "assemble",
    icon: "flip",
    badge: "Mirror",
    badgeTone: "slate",
    footer: "H / V flip",
    tag: "Vector flip",
    searchText: "flip pdf mirror horizontal vertical reflect",
  },
  {
    id: "n-up",
    name: "Pages Per Sheet",
    description: "2/4/6/9/16-up handouts on A4, Letter, or Legal.",
    href: "/pdf-tools/n-up",
    category: "assemble",
    icon: "dashboard",
    badge: "N-up",
    badgeTone: "tertiary",
    footer: "Vector embed & scale",
    tag: "Handouts",
    searchText: "n-up multiple pages per sheet handout 2-up 4-up contact sheet",
  },
  {
    id: "bates",
    name: "Bates Numbering",
    description: "Continuous Bates stamps across a multi-file production with CSV log.",
    href: "/pdf-tools/bates",
    category: "assemble",
    icon: "pin",
    badge: "Legal",
    badgeTone: "popular",
    footer: "Cross-file sequence",
    tag: "Production",
    searchText: "bates numbering legal discovery production stamp prefix",
  },
  {
    id: "compress",
    name: "Compress PDF",
    description: "Reduce PDF size, or split it into parts under a limit.",
    href: "/pdf-tools/compress",
    category: "assemble",
    icon: "compress",
    badge: "3 Presets",
    badgeTone: "tertiary",
    footer: "Adjustable DPI",
    tag: "Up to -80%",
    searchText: "compress pdf shrink size dpi presets",
  },
  {
    id: "page-numbers",
    name: "Add Page Numbers",
    description: "Number selected pages with custom placement and formatting.",
    href: "/pdf-tools/page-numbers",
    category: "assemble",
    icon: "format_list_numbered",
    badge: "Layout",
    badgeTone: "slate",
    footer: "6 Position presets",
    tag: "Bates / Rom",
    searchText: "add page numbers pagination footer bates roman",
  },
  {
    id: "crop",
    name: "Crop PDF",
    description: "Trim unwanted margins from selected pages without rasterising.",
    href: "/pdf-tools/crop",
    category: "assemble",
    icon: "crop",
    badge: "Lossless",
    badgeTone: "slate",
    footer: "Vector fidelity retained",
    tag: "Box Model",
    searchText: "crop pdf margins trim lossless",
  },
  {
    id: "edit",
    name: "Edit PDF",
    description: "Add text, drawings, highlights, shapes, redaction, and images visually.",
    href: "/pdf-tools/edit",
    category: "edit",
    icon: "draw",
    badge: "Full Suite",
    badgeTone: "primaryFixed",
    footer: "In-browser canvas",
    tag: "Vector Layers",
    searchText: "edit pdf text redaction highlights drawings shapes images",
  },
  {
    id: "sign",
    name: "Sign PDF",
    description: "Draw and place a visible signature without uploading.",
    href: "/pdf-tools/sign",
    category: "edit",
    icon: "signature",
    badge: "Private",
    badgeTone: "popular",
    footer: "Zero cloud storage",
    tag: "Cryptographic",
    searchText: "sign pdf digital signature draw private",
  },
  {
    id: "watermark",
    name: "Watermark PDF",
    description: "Add text or an image watermark without uploading the document.",
    href: "/pdf-tools/watermark",
    category: "edit",
    icon: "branding_watermark",
    badge: "Text & Image",
    badgeTone: "slate",
    footer: "Opacity & angle control",
    tag: "Alpha Blend",
    searchText: "watermark pdf stamp overlay text image",
  },
  {
    id: "metadata",
    name: "Edit Metadata",
    description: "Update the PDF title, author, subject, and keywords.",
    href: "/pdf-tools/metadata",
    category: "edit",
    icon: "manage_search",
    badge: "Sanitize",
    badgeTone: "slate",
    footer: "Metadata cleaning",
    tag: "XMP & Info",
    searchText: "edit metadata author title subject keywords sanitize",
  },
  {
    id: "flatten",
    name: "Flatten PDF",
    description: "Bake forms, annotations, and edits into fixed page images.",
    href: "/pdf-tools/flatten",
    category: "edit",
    icon: "layers_clear",
    badge: "Archive",
    badgeTone: "slate",
    footer: "Image bake",
    tag: "Secure flatten",
    searchText: "flatten pdf forms annotations acroform lock archive raster",
  },
  {
    id: "pdf-to-text",
    name: "PDF OCR",
    description:
      "Extract text or save a searchable PDF from scanned English, Hindi, and Marathi pages.",
    href: "/pdf-tools/pdf-to-text",
    category: "convert",
    icon: "document_scanner",
    badge: "EN · HI · MR",
    badgeTone: "popular",
    footer: "On-device OCR",
    tag: "Neural OCR",
    searchText: "pdf ocr text recognition tesseract english hindi marathi searchable",
    iconTone: "amber",
  },

  {
    id: "ai-summary",
    name: "AI Summary of PDF",
    description: "Private on-device summary — text layer first, auto-OCR for scans.",
    href: "/pdf-tools/ai-summary",
    category: "convert",
    icon: "auto_awesome",
    badge: "On-device",
    badgeTone: "popular",
    footer: "Runs in your browser",
    tag: "Private summary",
    searchText: "ai summary summarise summarize pdf private on-device extractive textrank ocr tesseract scan",
    iconTone: "amber",
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Turn PDF text and scanned pages into an editable Word document.",
    href: "/pdf-tools/pdf-to-word",
    category: "convert",
    icon: "description",
    badge: "DOCX",
    badgeTone: "slate",
    footer: "Local paragraph parsing",
    tag: "Clean Styles",
    searchText: "pdf to word docx export document",
  },
  {
    id: "images-to-pdf",
    name: "Images to PDF",
    description: "Turn JPG, PNG, and WebP images into one clean PDF document.",
    href: "/pdf-tools/images-to-pdf",
    category: "convert",
    icon: "photo_library",
    badge: "Batch",
    badgeTone: "slate",
    footer: "Custom margins & order",
    tag: "WebP+PNG",
    searchText: "images to pdf jpg png webp batch",
  },
  {
    id: "pdf-to-images",
    name: "PDF to Images",
    description: "Export selected pages as PNG, JPG, or WebP images.",
    href: "/pdf-tools/pdf-to-images",
    category: "convert",
    icon: "image",
    badge: "High DPI",
    badgeTone: "slate",
    footer: "Lossless canvas render",
    tag: "300 DPI Zip",
    searchText: "pdf to images export png jpg webp high dpi",
  },
  {
    id: "scan-to-pdf",
    name: "Scan to PDF",
    description: "Camera or gallery capture, crop edges, enhance, and save a multi-page PDF.",
    href: "/pdf-tools/scan-to-pdf",
    category: "convert",
    icon: "photo_camera",
    badge: "Camera",
    badgeTone: "popular",
    footer: "No app install",
    tag: "Document scan",
    searchText: "scan to pdf camera gallery document capture crop enhance",
    iconTone: "amber",
  },
  {
    id: "pdf-to-handwriting",
    name: "PDF to Handwriting",
    description: "Turn PDF text into notebook-style handwritten notes on this device.",
    href: "/pdf-tools/pdf-to-handwriting",
    category: "convert",
    icon: "edit",
    badge: "Notebook",
    badgeTone: "primaryFixed",
    footer: "On-device Caveat font",
    tag: "Handwritten",
    searchText: "pdf to handwriting notebook notes handwritten caveat",
  },
  {
    id: "grayscale",
    name: "Grayscale PDF",
    description: "Convert colour pages to print-friendly grayscale.",
    href: "/pdf-tools/grayscale",
    category: "convert",
    icon: "filter_b_and_w",
    badge: "Print Ready",
    badgeTone: "slate",
    footer: "Conserves ink & toner",
    tag: "Mono 8-bit",
    searchText: "grayscale pdf black and white print toner colour color",
  },
  {
    id: "repair",
    name: "Repair PDF",
    description: "Rebuild a PDF with a fresh, cleaner internal structure.",
    href: "/pdf-tools/repair",
    category: "secure",
    icon: "build_circle",
    badge: "XREF Fix",
    badgeTone: "popular",
    footer: "Structural recovery",
    tag: "Stream Repair",
    searchText: "repair pdf fix corrupt xref table structure",
  },
  {
    id: "unlock",
    name: "Remove Password",
    description: "Remove an open password by rebuilding an authorised local copy.",
    href: "/pdf-tools/unlock",
    category: "secure",
    icon: "lock_open",
    badge: "Authorised",
    badgeTone: "slate",
    footer: "Instant local rebuild",
    tag: "Auth Decrypt",
    searchText: "remove password unlock decrypt authorised authorized",
  },
  {
    id: "lock",
    name: "Add Password",
    description: "Add an open password with local 256-bit PDF encryption.",
    href: "/pdf-tools/lock",
    category: "secure",
    icon: "lock",
    badge: "AES-256",
    badgeTone: "slate",
    footer: "Zero server passphrases",
    tag: "FIPS Standard",
    searchText: "add password encrypt lock aes 256 fips",
  },
];

export const STITCH_TOOL_COUNT = stitchTools.length;
