export type StitchCategoryId = "assemble" | "edit" | "convert" | "secure";

export type StitchBadgeTone = "brand" | "slate" | "emerald" | "amber";

export type StitchTool = {
  id: string;
  name: string;
  description: string;
  href: string;
  category: StitchCategoryId;
  icon: string;
  badge: string;
  badgeTone: StitchBadgeTone;
  footer: string;
  searchText: string;
  iconTone?: "brand" | "amber";
};

export type StitchCategory = {
  id: StitchCategoryId;
  title: string;
  blurb: string;
  icon: string;
  count: number;
};

export const stitchCategories: StitchCategory[] = [
  {
    id: "assemble",
    title: "Assemble",
    blurb: "Combine, split, extract, and arrange pages",
    icon: "layers",
    count: 6,
  },
  {
    id: "edit",
    title: "Edit & Sign",
    blurb: "Annotate, redact, stamp, and fill documents",
    icon: "edit_note",
    count: 5,
  },
  {
    id: "convert",
    title: "Convert",
    blurb: "Format conversion, OCR extraction, and image exports",
    icon: "sync_alt",
    count: 5,
  },
  {
    id: "secure",
    title: "Security & Repair",
    blurb: "Local cryptographic lock, unlock, and document repair",
    icon: "security",
    count: 3,
  },
];

export const stitchTools: StitchTool[] = [
  {
    id: "merge",
    name: "Merge PDF",
    description: "Combine PDFs and images in your exact sequence.",
    href: "/pdf-tools/merge",
    category: "assemble",
    icon: "call_merge",
    badge: "Popular",
    badgeTone: "brand",
    footer: "Lossless stitching",
    searchText: "merge pdf combine losslessly",
  },
  {
    id: "split",
    name: "Split & Extract",
    description: "Save page ranges or individual leaves as new files.",
    href: "/pdf-tools/split",
    category: "assemble",
    icon: "content_cut",
    badge: "Precise",
    badgeTone: "slate",
    footer: "Custom page ranges",
    searchText: "split and extract pages",
  },
  {
    id: "organise",
    name: "Organise Pages",
    description: "Reorder, rotate, or delete pages with live preview.",
    href: "/pdf-tools/organise",
    category: "assemble",
    icon: "dashboard_customize",
    badge: "Visual",
    badgeTone: "emerald",
    footer: "Drag & reorder",
    searchText: "organise organize pages visual reorder",
  },
  {
    id: "compress",
    name: "Compress PDF",
    description: "Reduce file size significantly or split by MB limit.",
    href: "/pdf-tools/compress",
    category: "assemble",
    icon: "compress",
    badge: "3 Presets",
    badgeTone: "brand",
    footer: "Adjustable DPI",
    searchText: "compress pdf shrink size dpi",
  },
  {
    id: "page-numbers",
    name: "Page Numbers",
    description: "Add numbering with custom position, font, and format.",
    href: "/pdf-tools/page-numbers",
    category: "assemble",
    icon: "format_list_numbered",
    badge: "Layout",
    badgeTone: "slate",
    footer: "6 Position presets",
    searchText: "add page numbers pagination footer",
  },
  {
    id: "crop",
    name: "Crop PDF",
    description: "Trim unwanted margins while preserving vector quality.",
    href: "/pdf-tools/crop",
    category: "assemble",
    icon: "crop",
    badge: "Lossless",
    badgeTone: "slate",
    footer: "Vector fidelity retained",
    searchText: "crop pdf margins trim",
  },
  {
    id: "edit",
    name: "Edit PDF",
    description: "Insert text, shapes, highlights, redactions, and images.",
    href: "/pdf-tools/edit",
    category: "edit",
    icon: "edit",
    badge: "Full Suite",
    badgeTone: "brand",
    footer: "In-browser canvas",
    searchText: "edit pdf text redaction highlights",
  },
  {
    id: "sign",
    name: "Sign PDF",
    description: "Draw and place visible signatures without saving signatures remotely.",
    href: "/pdf-tools/sign",
    category: "edit",
    icon: "signature",
    badge: "Private",
    badgeTone: "emerald",
    footer: "Zero cloud storage",
    searchText: "sign pdf digital signature draw",
  },
  {
    id: "watermark",
    name: "Watermark PDF",
    description: "Apply recurring custom text or logo stamps across pages.",
    href: "/pdf-tools/watermark",
    category: "edit",
    icon: "branding_watermark",
    badge: "Text & Image",
    badgeTone: "slate",
    footer: "Opacity & angle control",
    searchText: "watermark pdf stamp overlay",
  },
  {
    id: "flatten",
    name: "Flatten Forms",
    description: "Lock fillable fields into uneditable permanent page content.",
    href: "/pdf-tools/flatten",
    category: "edit",
    icon: "check_box",
    badge: "Archive",
    badgeTone: "slate",
    footer: "Compliance lock",
    searchText: "flatten forms acroform lock",
  },
  {
    id: "metadata",
    name: "Edit Metadata",
    description: "Inspect and strip author, producer, title, and keywords.",
    href: "/pdf-tools/metadata",
    category: "edit",
    icon: "info",
    badge: "Sanitize",
    badgeTone: "slate",
    footer: "Metadata cleaning",
    searchText: "edit metadata author title sanitize",
  },
  {
    id: "pdf-to-text",
    name: "PDF OCR",
    description: "Extract text or make scanned pages searchable with local OCR.",
    href: "/pdf-tools/pdf-to-text",
    category: "convert",
    icon: "document_scanner",
    badge: "EN · HI · MR",
    badgeTone: "amber",
    footer: "Tesseract Wasm Engine",
    searchText: "pdf ocr text recognition tesseract english hindi marathi",
    iconTone: "amber",
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert layout & paragraphs into an editable DOCX format.",
    href: "/pdf-tools/pdf-to-word",
    category: "convert",
    icon: "article",
    badge: "DOCX",
    badgeTone: "slate",
    footer: "Local paragraph parsing",
    searchText: "pdf to word docx export document",
  },
  {
    id: "images-to-pdf",
    name: "Images to PDF",
    description: "Combine JPG, PNG, and WebP sets into a single PDF.",
    href: "/pdf-tools/images-to-pdf",
    category: "convert",
    icon: "photo_library",
    badge: "Batch",
    badgeTone: "slate",
    footer: "Custom margins & order",
    searchText: "images to pdf jpg png webp",
  },
  {
    id: "pdf-to-images",
    name: "PDF to Images",
    description: "Export individual pages as crisp PNG, JPG, or WebP.",
    href: "/pdf-tools/pdf-to-images",
    category: "convert",
    icon: "image",
    badge: "High DPI",
    badgeTone: "slate",
    footer: "Lossless canvas render",
    searchText: "pdf to images export png jpg high dpi",
  },
  {
    id: "grayscale",
    name: "Grayscale PDF",
    description: "Strip colored inks to create monochrome, print-friendly copies.",
    href: "/pdf-tools/grayscale",
    category: "convert",
    icon: "filter_b_and_w",
    badge: "Print Ready",
    badgeTone: "slate",
    footer: "Conserves ink & toner",
    searchText: "grayscale pdf black and white print toner",
  },
  {
    id: "lock",
    name: "Add Password",
    description: "Encrypt documents with local 256-bit AES standard security.",
    href: "/pdf-tools/lock",
    category: "secure",
    icon: "lock",
    badge: "AES-256",
    badgeTone: "emerald",
    footer: "Zero server passphrases",
    searchText: "add password encrypt lock aes 256",
  },
  {
    id: "unlock",
    name: "Remove Password",
    description: "Rebuild an unlocked copy locally when authorized.",
    href: "/pdf-tools/unlock",
    category: "secure",
    icon: "lock_open",
    badge: "Authorised",
    badgeTone: "slate",
    footer: "Instant local rebuild",
    searchText: "remove password unlock decrypt authorised",
  },
  {
    id: "repair",
    name: "Repair PDF",
    description: "Reconstruct damaged cross-reference tables and corrupt trees.",
    href: "/pdf-tools/repair",
    category: "secure",
    icon: "build",
    badge: "XREF Fix",
    badgeTone: "slate",
    footer: "Structural recovery",
    searchText: "repair pdf fix corrupt xref table",
  },
];

export const STITCH_TOOL_COUNT = stitchTools.length;
